stages:
  preprocess:
    cmd: python src/data_preprocessing.py --input data/raw/iris.csv --output data/processed/iris.csv
    deps:
      - src/data_preprocessing.py
      - data/raw/iris.csv
    outs:
      - data/processed/iris.csv

  train:
    cmd: python src/train_model.py --data data/processed/iris.csv --output models/trained_model.pkl
    deps:
      - src/train_model.py
      - data/processed/iris.csv
    outs:
      - models/trained_model.pkl
